branches: 
  - main
repositoryUrl: https://github.com/liatrio/image-builder-openshift.git
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/github"
